"use client"

import { createContext, useContext, useState } from "react"

const LanguageContext = createContext()

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState("en")

  const changeLanguage = (newLanguage) => {
    setLanguage(newLanguage)
  }

  // Translations object
  const translations = {
    it: {
      myAccount: "Il Mio Account",
      manageProfile: "Gestisci il tuo profilo e le prenotazioni",
      memberSince: "Membro dal",
      firstName: "Nome",
      lastName: "Cognome",
      profile: "Profilo",
      personalInfo: "Informazioni Personali",
      editData: "Modifica i tuoi dati",
      saveChanges: "Salva modifiche",
      upcomingBookings: "Prossime Prenotazioni",
      completedBookings: "Prenotazioni Completate",
      cancelledBookings: "Prenotazioni Cancellate",
      noUpcomingBookings: "Non hai prenotazioni in programma",
      noCompletedBookings: "Non hai ancora completato prenotazioni",
      noCancelledBookings: "Non hai prenotazioni cancellate",
      viewBooking: "Vedi prenotazione",
      changePassword: "Cambia Password",
      newPassword: "Nuova Password",
      confirmNewPassword: "Conferma Nuova Password",
      currentPassword: "Password Attuale",
      deleteAccount: "Elimina Account",
      notifications: "Notifiche",
      enableDisableAlerts: "Abilita o disabilita gli avvisi",
      privacySecurity: "Privacy e Sicurezza",
      changePasswordOrDelete: "Cambia password o elimina il tuo account",
      specialOffers: "Offerte Speciali",
      savePreferences: "Salva Preferenze",
      bookingCancelled: "Prenotazione Cancellata",
      refundAmount: "Importo Rimborso",
      penalty: "Penale",
      cancelledOn: "Cancellata il",
      refundProcessing: "Il rimborso verrà elaborato entro 5-10 giorni lavorativi",
      profileUpdatedSuccess: "Profilo aggiornato con successo!",
      errorUpdatingProfile: "Errore durante l'aggiornamento del profilo",
      fillAllFields: "Compila tutti i campi",
      newPasswordMinLength: "La nuova password deve essere di almeno 6 caratteri",
      passwordChangedSuccess: "Password cambiata con successo!",
      currentPasswordWrong: "Password attuale errata",
      errorChangingPassword: "Errore durante il cambio password",
      fillAllRequiredFields: "Compila tutti i campi obbligatori",
      emailDoesNotMatch: "L'email non corrisponde",
      confirmDeleteAccount:
        "Sei sicuro di voler eliminare il tuo account? Questa azione è irreversibile e cancellerà tutti i tuoi dati e le prenotazioni passate.",
      accountDeletedSuccess: "Account eliminato con successo",
      wrongPassword: "Password errata",
      errorDeletingAccount: "Errore durante l'eliminazione dell'account",
      preferenceSavedSuccess: "Preferenze salvate con successo!",
      errorSavingPreferences: "Errore durante il salvataggio delle preferenze",
      paid: "Pagata",
      confirmed: "Confermata",
      completed: "Completata",
      cancelled: "Cancellata",
      bookingConfirmationEmail: "Email di conferma prenotazione",
      bookingConfirmationEmailDesc: "Riceverai sempre un'email di conferma per ogni prenotazione effettuata",
      checkInReminder: "Promemoria check-in",
      checkInReminderDesc: "Riceverai sempre un promemoria il giorno prima del tuo check-in",
      specialOffersDesc: "Offerte promozionali soggette a condizioni e disponibilità",
      night: "notte",
      nights: "notti",
      loading: "Caricamento...",
      error: "Errore",
      email: "Email",
      phone: "Telefono",
      address: "Indirizzo",
      cancel: "Annulla",
      edit: "Modifica",
      bookings: "Prenotazioni",
      settings: "Impostazioni",
      pending: "In attesa",
      bookingNotFound: "Prenotazione non trovata",
      backToProfile: "Torna al profilo",
      guest: "Ospite",
      bookingDetails: "Dettagli Prenotazione",
      confirmationNumber: "Numero di conferma",
      from15: "dalle ore 15:00",
      until10: "fino alle ore 10:00",
      guests: "Ospiti",
      person: "persona",
      people: "persone",
      specialRequests: "Richieste speciali",
      paymentInfo: "Informazioni sul Pagamento",
      originalCost: "Costo originale",
      cancellationPenalty: "Penale di cancellazione",
      refund: "Rimborso",
      totalCost: "Costo totale",
      totalPaid: "Totale pagato",
      remaining: "Rimanente",
      onlinePayment: "Pagamento online",
      fullPaymentMade: "Il pagamento completo è stato effettuato al momento della prenotazione.",
      manageBooking: "Gestisci la prenotazione",
      changeDates: "Cambia le date",
      addGuest: "Aggiungi ospite",
      cancelBooking: "Cancella la prenotazione",
      contactProperty: "Contatta la struttura",
      sendMessage: "Invia un messaggio",
      sendEmail: "Invia un'e-mail",
      addGuests: "Aggiungi ospiti",
      addGuestsDesc: "Puoi aggiungere fino a 2 ospite/i aggiuntivo/i.",
      newGuestsNumber: "Nuovo numero di ospiti",
      currently: "Attualmente",
      guestsCount: "ospite/i",
      calculateDifference: "Calcola differenza",
      changeDatesTitle: "Cambia le date della prenotazione",
      changeDatesDesc: "Seleziona le nuove date. Ti verrà mostrato il prezzo da pagare prima di confermare.",
      penalty50: "⚠ Penale del 50%",
      penalty50Desc:
        "Stai modificando le date a meno di 7 giorni dal check-in. Verrà applicata una penale del 50% dell'importo originale.",
      originalPrice: "Prezzo originale",
      newBasePrice: "Nuovo prezzo base",
      newTotalPrice: "Nuovo prezzo totale",
      priceDifference: "Differenza da pagare",
      confirmCancellation: "Conferma cancellazione",
      bookingCancelledSuccess: "Prenotazione cancellata con successo!",
      cancellationError: "Errore nella cancellazione",
      within: "entro",
      businessDays: "5-10 giorni lavorativi",
      extraServicesRequests: "Richieste Servizi Extra",
      extraServicesDesc: "Visualizza lo stato delle tue richieste di servizi aggiuntivi",
      noExtraServicesRequests: "Nessuna richiesta di servizi extra effettuata",
      requestFrom: "Richiesta del",
      servicesRequested: "servizi richiesti",
      managerWillRespond:
        "Il gestore ti risponderà via email per confermare la disponibilità e fornirti i dettagli di pagamento.",
      paymentCompleted: "Pagamento completato! Aggiornamento in corso...",
      updatingBooking: "Stiamo aggiornando la tua prenotazione. Attendi qualche secondo.",
      bookingUpdated: "Prenotazione aggiornata!",
      changesApplied: "Le modifiche sono state applicate con successo.",
      paymentReceived: "Pagamento ricevuto",
      bookingWillUpdate: "La prenotazione sarà aggiornata a breve.",
      paymentCancelled: "Pagamento annullato",
      tryAgainLater: "Il pagamento è stato annullato. Puoi riprovare quando vuoi.",
    },
    en: {
      myAccount: "My Account",
      manageProfile: "Manage your profile and bookings",
      memberSince: "Member since",
      firstName: "First Name",
      lastName: "Last Name",
      profile: "Profile",
      personalInfo: "Personal Information",
      editData: "Edit your data",
      saveChanges: "Save Changes",
      upcomingBookings: "Upcoming Bookings",
      completedBookings: "Completed Bookings",
      cancelledBookings: "Cancelled Bookings",
      noUpcomingBookings: "You have no upcoming bookings",
      noCompletedBookings: "You haven't completed any bookings yet",
      noCancelledBookings: "You have no cancelled bookings",
      viewBooking: "View booking",
      changePassword: "Change Password",
      newPassword: "New Password",
      confirmNewPassword: "Confirm New Password",
      currentPassword: "Current Password",
      deleteAccount: "Delete Account",
      notifications: "Notifications",
      enableDisableAlerts: "Enable or disable alerts",
      privacySecurity: "Privacy & Security",
      changePasswordOrDelete: "Change password or delete your account",
      specialOffers: "Special Offers",
      savePreferences: "Save Preferences",
      bookingCancelled: "Booking Cancelled",
      refundAmount: "Refund Amount",
      penalty: "Penalty",
      cancelledOn: "Cancelled on",
      refundProcessing: "Refund will be processed within 5-10 business days",
      profileUpdatedSuccess: "Profile updated successfully!",
      errorUpdatingProfile: "Error updating profile",
      fillAllFields: "Fill all fields",
      newPasswordMinLength: "New password must be at least 6 characters",
      passwordChangedSuccess: "Password changed successfully!",
      currentPasswordWrong: "Current password is incorrect",
      errorChangingPassword: "Error changing password",
      fillAllRequiredFields: "Fill all required fields",
      emailDoesNotMatch: "Email does not match",
      confirmDeleteAccount:
        "Are you sure you want to delete your account? This action is irreversible and will delete all your data and past bookings.",
      accountDeletedSuccess: "Account deleted successfully",
      wrongPassword: "Wrong password",
      errorDeletingAccount: "Error deleting account",
      preferenceSavedSuccess: "Preferences saved successfully!",
      errorSavingPreferences: "Error saving preferences",
      paid: "Paid",
      confirmed: "Confirmed",
      completed: "Completed",
      cancelled: "Cancelled",
      bookingConfirmationEmail: "Booking confirmation email",
      bookingConfirmationEmailDesc: "You will always receive a confirmation email for each booking made",
      checkInReminder: "Check-in reminder",
      checkInReminderDesc: "You will always receive a reminder the day before your check-in",
      specialOffersDesc: "Promotional offers subject to conditions and availability",
      night: "night",
      nights: "nights",
      loading: "Loading...",
      error: "Error",
      email: "Email",
      phone: "Phone",
      address: "Address",
      cancel: "Cancel",
      edit: "Edit",
      bookings: "Bookings",
      settings: "Settings",
      pending: "Pending",
      bookingNotFound: "Booking not found",
      backToProfile: "Back to profile",
      guest: "Guest",
      bookingDetails: "Booking Details",
      confirmationNumber: "Confirmation number",
      from15: "from 3:00 PM",
      until10: "until 10:00 AM",
      guests: "Guests",
      person: "person",
      people: "people",
      specialRequests: "Special requests",
      paymentInfo: "Payment Information",
      originalCost: "Original cost",
      cancellationPenalty: "Cancellation penalty",
      refund: "Refund",
      totalCost: "Total cost",
      totalPaid: "Total paid",
      remaining: "Remaining",
      onlinePayment: "Online payment",
      fullPaymentMade: "Full payment was made at the time of booking.",
      manageBooking: "Manage booking",
      changeDates: "Change dates",
      addGuest: "Add guest",
      cancelBooking: "Cancel booking",
      contactProperty: "Contact property",
      sendMessage: "Send a message",
      sendEmail: "Send an email",
      addGuests: "Add Guests",
      addGuestsDesc: "You can add up to 2 additional guest(s).",
      newGuestsNumber: "New number of guests",
      currently: "Currently",
      guestsCount: "guest(s)",
      calculateDifference: "Calculate difference",
      changeDatesTitle: "Change booking dates",
      changeDatesDesc: "Select the new dates. You will be shown the price before confirming.",
      penalty50: "⚠ 50% Penalty",
      penalty50Desc:
        "You are modifying dates less than 7 days before check-in. A 50% penalty of the original amount will be applied.",
      originalPrice: "Original price",
      newBasePrice: "New base price",
      newTotalPrice: "New total price",
      priceDifference: "Difference to pay",
      confirmCancellation: "Confirm cancellation",
      bookingCancelledSuccess: "Booking cancelled successfully!",
      cancellationError: "Cancellation error",
      within: "within",
      businessDays: "5-10 business days",
      extraServicesRequests: "Extra Services Requests",
      extraServicesDesc: "View the status of your additional services requests",
      noExtraServicesRequests: "No extra services requests made",
      requestFrom: "Request from",
      servicesRequested: "services requested",
      service: "service",
      services: "services",
      notes: "Notes",
      estimatedTotal: "Estimated Total",
      managerWillRespond: "The manager will contact you via email to confirm availability and provide payment details.",
      paymentCompleted: "Payment completed! Updating...",
      updatingBooking: "We're updating your booking. Please wait a moment.",
      bookingUpdated: "Booking updated!",
      changesApplied: "Changes applied successfully.",
      paymentReceived: "Payment received",
      bookingWillUpdate: "The booking will be updated shortly.",
      paymentCancelled: "Payment cancelled",
      tryAgainLater: "Payment was cancelled. You can try again later.",
    },
    fr: {
      myAccount: "Mon Compte",
      manageProfile: "Gérez votre profil et vos réservations",
      memberSince: "Membre depuis",
      firstName: "Prénom",
      lastName: "Nom",
      profile: "Profil",
      personalInfo: "Informations Personnelles",
      editData: "Modifiez vos données",
      saveChanges: "Sauvegarder",
      upcomingBookings: "Réservations à Venir",
      completedBookings: "Réservations Terminées",
      cancelledBookings: "Réservations Annulées",
      noUpcomingBookings: "Vous n'avez aucune réservation à venir",
      noCompletedBookings: "Vous n'avez pas encore de réservations terminées",
      noCancelledBookings: "Vous n'avez pas de réservations annulées",
      viewBooking: "Voir la réservation",
      changePassword: "Changer le Mot de Passe",
      newPassword: "Nouveau Mot de Passe",
      confirmNewPassword: "Confirmer le Nouveau Mot de Passe",
      currentPassword: "Mot de Passe Actuel",
      deleteAccount: "Supprimer le Compte",
      notifications: "Notifications",
      enableDisableAlerts: "Activer ou désactiver les alertes",
      privacySecurity: "Confidentialité et Sécurité",
      changePasswordOrDelete: "Changer le mot de passe ou supprimer votre compte",
      specialOffers: "Offres Spéciales",
      savePreferences: "Sauvegarder les Préférences",
      bookingCancelled: "Réservation Annulée",
      refundAmount: "Montant du Remboursement",
      penalty: "Pénalité",
      cancelledOn: "Annulée le",
      refundProcessing: "Le remboursement sera traité sous 5-10 jours ouvrables",
      profileUpdatedSuccess: "Profil mis à jour avec succès!",
      errorUpdatingProfile: "Erreur lors de la mise à jour du profil",
      fillAllFields: "Remplissez tous les champs",
      newPasswordMinLength: "Le nouveau mot de passe doit contenir au moins 6 caractères",
      passwordChangedSuccess: "Mot de passe changé avec succès!",
      currentPasswordWrong: "Le mot de passe actuel est incorrect",
      errorChangingPassword: "Erreur lors du changement de mot de passe",
      fillAllRequiredFields: "Remplissez tous les champs obligatoires",
      emailDoesNotMatch: "E-Mail stimmt nicht überein",
      confirmDeleteAccount:
        "Êtes-vous sûr de vouloir supprimer votre compte? Cette action est irréversible et supprimera toutes vos données et réservations passées.",
      accountDeletedSuccess: "Compte supprimé avec succès",
      wrongPassword: "Mot de passe incorrect",
      errorDeletingAccount: "Erreur lors de la suppression du compte",
      preferenceSavedSuccess: "Préférences enregistrées avec succès!",
      errorSavingPreferences: "Erreur lors de l'enregistrement des préférences",
      paid: "Payée",
      confirmed: "Confirmée",
      completed: "Terminée",
      cancelled: "Annulée",
      bookingConfirmationEmail: "Email de confirmation de réservation",
      bookingConfirmationEmailDesc: "Vous recevrez toujours un email de confirmation pour chaque réservation effectuée",
      checkInReminder: "Rappel de check-in",
      checkInReminderDesc: "Vous recevrez toujours un rappel la veille de votre check-in",
      specialOffersDesc: "Offres promotionnelles soumises à conditions et disponibilité",
      night: "Nacht",
      nights: "Nächte",
      loading: "Chargement...",
      error: "Erreur",
      email: "E-Mail",
      phone: "Telefon",
      address: "Adresse",
      cancel: "Annuler",
      edit: "Bearbeiten",
      bookings: "Réservations",
      settings: "Paramètres",
      pending: "En attente",
      bookingNotFound: "Réservation non trouvée",
      backToProfile: "Retour au profil",
      guest: "Invité",
      bookingDetails: "Détails de la Réservation",
      confirmationNumber: "Numéro de confirmation",
      from15: "à partir de 15h00",
      until10: "jusqu'à 10h00",
      guests: "Invités",
      person: "personne",
      people: "personnes",
      specialRequests: "Demandes spéciales",
      paymentInfo: "Informations de Paiement",
      originalCost: "Coût original",
      cancellationPenalty: "Pénalité d'annulation",
      refund: "Remboursement",
      totalCost: "Coût total",
      totalPaid: "Total payé",
      remaining: "Restant",
      onlinePayment: "Paiement en ligne",
      fullPaymentMade: "Le paiement complet a été effectué au moment de la réservation.",
      manageBooking: "Gérer la réservation",
      changeDates: "Changer les dates",
      addGuest: "Ajouter un invité",
      cancelBooking: "Annuler la réservation",
      contactProperty: "Contacter l'établissement",
      sendMessage: "Envoyer un message",
      sendEmail: "Envoyer un email",
      addGuests: "Ajouter des invités",
      addGuestsDesc: "Vous pouvez ajouter jusqu'à 2 invité(s) supplémentaire(s).",
      newGuestsNumber: "Nouveau nombre d'invités",
      currently: "Actuellement",
      guestsCount: "Gast/Gäste",
      calculateDifference: "Calculer la différence",
      changeDatesTitle: "Modifier les dates de réservation",
      changeDatesDesc: "Sélectionnez les nouvelles dates. Le prix vous sera affiché avant confirmation.",
      penalty50: "⚠ Pénalité de 50%",
      penalty50Desc:
        "Vous modifiez les dates moins de 7 jours avant l'arrivée. Une pénalité de 50% du montant original sera appliquée.",
      originalPrice: "Prix original",
      newBasePrice: "Nouveau prix de base",
      newTotalPrice: "Nouveau prix total",
      priceDifference: "Différence à payer",
      confirmCancellation: "Stornierung bestätigen",
      bookingCancelledSuccess: "Réservation annulée avec succès!",
      cancellationError: "Erreur d'annulation",
      within: "dans",
      businessDays: "5-10 jours ouvrables",
      extraServicesRequests: "Demandes de Services Supplémentaires",
      extraServicesDesc: "Consultez l'état de vos demandes de services supplémentaires",
      noExtraServicesRequests: "Aucune demande de services supplémentaires effectuée",
      requestFrom: "Demande du",
      servicesRequested: "services demandés",
      managerWillRespond:
        "Le gestionnaire vous répondra par e-mail pour confirmer la disponibilité et vous fournir les détails de paiement.",
      paymentCompleted: "Paiement effectué! Mise à jour...",
      updatingBooking: "Nous mettons à jour votre réservation. Veuillez patienter.",
      bookingUpdated: "Réservation mise à jour!",
      changesApplied: "Modifications appliquées avec succès.",
      paymentReceived: "Paiement reçu",
      bookingWillUpdate: "La réservation sera mise à jour sous peu.",
      paymentCancelled: "Paiement annulé",
      tryAgainLater: "Le paiement a été annulé. Vous pouvez réessayer plus tard.",
    },
    es: {
      myAccount: "Mi Cuenta",
      manageProfile: "Gestiona tu perfil y reservas",
      memberSince: "Miembro desde",
      firstName: "Nombre",
      lastName: "Apellido",
      profile: "Perfil",
      personalInfo: "Información Personal",
      editData: "Edita tus datos",
      saveChanges: "Guardar Cambios",
      upcomingBookings: "Próximas Reservas",
      completedBookings: "Reservas Completadas",
      cancelledBookings: "Reservas Canceladas",
      noUpcomingBookings: "No tienes reservas próximas",
      noCompletedBookings: "Aún no has completado ninguna reserva",
      noCancelledBookings: "No tienes reservas canceladas",
      viewBooking: "Ver reserva",
      changePassword: "Cambiar Contraseña",
      newPassword: "Nueva Contraseña",
      confirmNewPassword: "Confirmar Nueva Contraseña",
      currentPassword: "Contraseña Actual",
      deleteAccount: "Eliminar Cuenta",
      notifications: "Notificaciones",
      enableDisableAlerts: "Activar o desactivar alertas",
      privacySecurity: "Privacidad y Seguridad",
      changePasswordOrDelete: "Cambiar contraseña o eliminar tu cuenta",
      specialOffers: "Ofertas Especiales",
      savePreferences: "Guardar Preferencias",
      bookingCancelled: "Reserva Cancelada",
      refundAmount: "Importe del Reembolso",
      penalty: "Penalización",
      cancelledOn: "Cancelada el",
      refundProcessing: "El reembolso se procesará en un plazo de 5-10 días hábiles",
      profileUpdatedSuccess: "Perfil actualizado con éxito!",
      errorUpdatingProfile: "Error al actualizar el perfil",
      fillAllFields: "Completa todos los campos",
      newPasswordMinLength: "La nueva contraseña debe tener al menos 6 caracteres",
      passwordChangedSuccess: "Contraseña cambiada con éxito!",
      currentPasswordWrong: "La contraseña actual es incorrecta",
      errorChangingPassword: "Error al cambiar la contraseña",
      fillAllRequiredFields: "Completa todos los campos obligatorios",
      emailDoesNotMatch: "El email no coincide",
      confirmDeleteAccount:
        "¿Estás seguro de que quieres eliminar tu cuenta? Esta acción es irreversible y eliminará todos tus datos y reservas pasadas.",
      accountDeletedSuccess: "Cuenta eliminada con éxito",
      wrongPassword: "Contraseña incorrecta",
      errorDeletingAccount: "Error al eliminar la cuenta",
      preferenceSavedSuccess: "Preferencias guardadas con éxito!",
      errorSavingPreferences: "Error al guardar las preferencias",
      paid: "Pagada",
      confirmed: "Confirmada",
      completed: "Completada",
      cancelled: "Cancelada",
      bookingConfirmationEmail: "Email de confirmación de reserva",
      bookingConfirmationEmailDesc: "Siempre recibirás un email de confirmación por cada reserva realizada",
      checkInReminder: "Recordatorio de check-in",
      checkInReminderDesc: "Siempre recibirás un recordatorio el día antes de tu check-in",
      specialOffersDesc: "Ofertas promocionales sujetas a condiciones y disponibilidad",
      night: "noche",
      nights: "noches",
      loading: "Cargando...",
      error: "Error",
      email: "Correo electrónico",
      phone: "Teléfono",
      address: "Dirección",
      cancel: "Cancelar",
      edit: "Editar",
      bookings: "Reservas",
      settings: "Configuración",
      pending: "Pendiente",
      bookingNotFound: "Reserva no encontrada",
      backToProfile: "Volver al perfil",
      guest: "Huésped",
      bookingDetails: "Detalles de la Reserva",
      confirmationNumber: "Número de confirmación",
      from15: "desde las 15:00",
      until10: "hasta las 10:00",
      guests: "Huéspedes",
      person: "persona",
      people: "personas",
      specialRequests: "Solicitudes especiales",
      paymentInfo: "Información de Pago",
      originalCost: "Costo original",
      cancellationPenalty: "Penalización por cancelación",
      refund: "Reembolso",
      totalCost: "Costo total",
      totalPaid: "Total pagado",
      remaining: "Restante",
      onlinePayment: "Pago en línea",
      fullPaymentMade: "El pago completo se realizó al momento de la reserva.",
      manageBooking: "Gestionar reserva",
      changeDates: "Cambiar fechas",
      addGuest: "Agregar huésped",
      cancelBooking: "Cancelar reserva",
      contactProperty: "Contactar propiedad",
      sendMessage: "Enviar un mensaje",
      sendEmail: "Enviar un correo electrónico",
      addGuests: "Añadir huéspedes",
      addGuestsDesc: "Puedes añadir hasta 2 huésped(es) adicional(es).",
      newGuestsNumber: "Nuevo número de huéspedes",
      currently: "Actualmente",
      guestsCount: "huésped(es)",
      calculateDifference: "Calcular diferencia",
      changeDatesTitle: "Cambiar fechas de reserva",
      changeDatesDesc: "Selecciona las nuevas fechas. Se te mostrará el precio antes de confirmar.",
      penalty50: "⚠ Penalización del 50%",
      penalty50Desc:
        "Estás modificando las fechas a menos de 7 días del check-in. Se aplicará una penalización del 50% del importe original.",
      originalPrice: "Precio original",
      newBasePrice: "Nuevo precio base",
      newTotalPrice: "Nuevo precio total",
      priceDifference: "Diferencia a pagar",
      confirmCancellation: "Confirmar cancelación",
      bookingCancelledSuccess: "Reserva cancelada con éxito!",
      cancellationError: "Error en la cancelación",
      within: "dentro de",
      businessDays: "5-10 días hábiles",
      extraServicesRequests: "Solicitudes de Servicios Extra",
      extraServicesDesc: "Ver el estado de tus solicitudes de servicios adicionales",
      noExtraServicesRequests: "No se han realizado solicitudes de servicios extra",
      requestFrom: "Solicitud del",
      servicesRequested: "servicios solicitados",
      managerWillRespond:
        "El gerente te responderá por correo electrónico para confirmar la disponibilidad y proporcionar los detalles de pago.",
      paymentCompleted: "Pago completado! Actualizando...",
      updatingBooking: "Estamos actualizando tu reserva. Espera un momento.",
      bookingUpdated: "Reserva actualizada!",
      changesApplied: "Cambios aplicados con éxito.",
      paymentReceived: "Pago recibido",
      bookingWillUpdate: "La reserva se actualizará en breve.",
      paymentCancelled: "Pago cancelado",
      tryAgainLater: "El pago fue cancelado. Puedes intentar más tarde.",
    },
    de: {
      myAccount: "Mein Konto",
      manageProfile: "Verwalten Sie Ihr Profil und Ihre Buchungen",
      memberSince: "Mitglied seit",
      firstName: "Vorname",
      lastName: "Nachname",
      profile: "Profil",
      personalInfo: "Persönliche Informationen",
      editData: "Ihre Daten bearbeiten",
      saveChanges: "Änderungen Speichern",
      upcomingBookings: "Kommende Buchungen",
      completedBookings: "Abgeschlossene Buchungen",
      cancelledBookings: "Stornierte Buchungen",
      noUpcomingBookings: "Sie haben keine bevorstehenden Buchungen",
      noCompletedBookings: "Sie haben noch keine Buchungen abgeschlossen",
      noCancelledBookings: "Sie haben keine stornierten Buchungen",
      viewBooking: "Buchung ansehen",
      changePassword: "Passwort Ändern",
      newPassword: "Neues Passwort",
      confirmNewPassword: "Neues Passwort Bestätigen",
      currentPassword: "Aktuelles Passwort",
      deleteAccount: "Konto Löschen",
      notifications: "Benachrichtigungen",
      enableDisableAlerts: "Warnungen aktivieren oder deaktivieren",
      privacySecurity: "Privatsphäre und Sicherheit",
      changePasswordOrDelete: "Passwort ändern oder Konto löschen",
      specialOffers: "Sonderangebote",
      savePreferences: "Einstellungen Speichern",
      bookingCancelled: "Buchung Storniert",
      refundAmount: "Rückerstattungsbetrag",
      penalty: "Strafgebühr",
      cancelledOn: "Storniert am",
      refundProcessing: "Die Rückerstattung wird innerhalb von 5-10 Werktagen bearbeitet",
      profileUpdatedSuccess: "Profil erfolgreich aktualisiert!",
      errorUpdatingProfile: "Fehler beim Aktualisieren des Profils",
      fillAllFields: "Alle Felder ausfüllen",
      newPasswordMinLength: "Das neue Passwort muss mindestens 6 Zeichen lang sein",
      passwordChangedSuccess: "Passwort erfolgreich geändert!",
      currentPasswordWrong: "Aktuelles Passwort ist falsch",
      errorChangingPassword: "Fehler beim Ändern des Passworts",
      fillAllRequiredFields: "Alle Pflichtfelder ausfüllen",
      emailDoesNotMatch: "E-Mail stimmt nicht überein",
      confirmDeleteAccount:
        "Sind Sie sicher, dass Sie Ihr Konto löschen möchten? Diese Aktion ist unwiderruflich und löscht alle Ihre Daten und vergangenen Buchungen.",
      accountDeletedSuccess: "Konto erfolgreich gelöscht",
      wrongPassword: "Falsches Passwort",
      errorDeletingAccount: "Fehler beim Löschen des Kontos",
      preferenceSavedSuccess: "Einstellungen erfolgreich gespeichert!",
      errorSavingPreferences: "Fehler beim Speichern der Einstellungen",
      paid: "Bezahlt",
      confirmed: "Bestätigt",
      completed: "Abgeschlossen",
      cancelled: "Storniert",
      bookingConfirmationEmail: "Buchungsbestätigungs-E-Mail",
      bookingConfirmationEmailDesc: "Sie erhalten immer eine Bestätigungs-E-Mail für jede Buchung",
      checkInReminder: "Check-in-Erinnerung",
      checkInReminderDesc: "Sie erhalten immer eine Erinnerung am Tag vor Ihrem Check-in",
      specialOffersDesc: "Aktionsangebote vorbehaltlich Bedingungen und Verfügbarkeit",
      night: "Nacht",
      nights: "Nächte",
      loading: "Wird geladen...",
      error: "Fehler",
      email: "E-Mail",
      phone: "Telefon",
      address: "Adresse",
      cancel: "Abbrechen",
      edit: "Bearbeiten",
      bookings: "Buchungen",
      settings: "Einstellungen",
      pending: "Ausstehend",
      bookingNotFound: "Buchung nicht gefunden",
      backToProfile: "Zurück zum Profil",
      guest: "Gast",
      bookingDetails: "Buchungsdetails",
      confirmationNumber: "Bestätigungsnummer",
      from15: "ab 15:00 Uhr",
      until10: "bis 10:00 Uhr",
      guests: "Gäste",
      person: "Person",
      people: "Personen",
      specialRequests: "Besondere Wünsche",
      paymentInfo: "Zahlungsinformationen",
      originalCost: "Ursprüngliche Kosten",
      cancellationPenalty: "Stornierungsgebühr",
      refund: "Rückerstattung",
      totalCost: "Gesamtkosten",
      totalPaid: "Insgesamt bezahlt",
      remaining: "Verbleibend",
      onlinePayment: "Online-Zahlung",
      fullPaymentMade: "Die vollständige Zahlung wurde zum Zeitpunkt der Buchung geleistet.",
      manageBooking: "Buchung verwalten",
      changeDates: "Daten ändern",
      addGuest: "Gast hinzufügen",
      cancelBooking: "Buchung stornieren",
      contactProperty: "Unterkunft kontaktieren",
      sendMessage: "Nachricht senden",
      sendEmail: "E-Mail senden",
      addGuests: "Gäste hinzufügen",
      addGuestsDesc: "Sie können bis zu 2 zusätzliche Gäst(e) hinzufügen.",
      newGuestsNumber: "Neue Anzahl von Gästen",
      currently: "Derzeit",
      guestsCount: "Gast/Gäste",
      calculateDifference: "Differenz berechnen",
      changeDatesTitle: "Buchungsdaten ändern",
      changeDatesDesc: "Wählen Sie die neuen Daten. Der Preis wird Ihnen vor der Bestätigung angezeigt.",
      penalty50: "⚠ 50% Strafe",
      penalty50Desc:
        "Sie ändern die Daten weniger als 7 Tage vor dem Check-in. Eine Strafe von 50% des Originalbetrags wird angewendet.",
      originalPrice: "Originalpreis",
      newBasePrice: "Neuer Grundpreis",
      newTotalPrice: "Neuer Gesamtpreis",
      priceDifference: "Zu zahlende Differenz",
      confirmCancellation: "Stornierung bestätigen",
      bookingCancelledSuccess: "Buchung erfolgreich storniert!",
      cancellationError: "Stornierungsfehler",
      within: "innerhalb",
      businessDays: "5-10 Werktage",
      extraServicesRequests: "Anfragen für Zusatzleistungen",
      extraServicesDesc: "Sehen Sie den Status Ihrer Anfragen für zusätzliche Dienstleistungen",
      noExtraServicesRequests: "Keine Anfragen für Zusatzleistungen gestellt",
      requestFrom: "Anfrage vom",
      servicesRequested: "Dienstleistungen angefordert",
      service: "Dienstleistung",
      services: "Dienstleistungen",
      notes: "Notizen",
      estimatedTotal: "Geschätzter Gesamtbetrag",
      managerWillRespond:
        "Der Manager wird Ihnen per E-Mail antworten, um die Verfügbarkeit zu bestätigen und Zahlungsdetails bereitzustellen.",
      paymentCompleted: "Zahlung abgeschlossen! Aktualisierung...",
      updatingBooking: "Wir aktualisieren Ihre Buchung. Bitte warten Sie einen Moment.",
      bookingUpdated: "Buchung aktualisiert!",
      changesApplied: "Änderungen erfolgreich übernommen.",
      paymentReceived: "Zahlung erhalten",
      bookingWillUpdate: "Die Buchung wird in Kürze aktualisiert.",
      paymentCancelled: "Zahlung storniert",
      tryAgainLater: "Die Zahlung wurde storniert. Sie können es später erneut versuchen.",
    },
  }

  const currentLanguage = translations[language]

  const t = (key: string, fallback?: string): string => {
    return currentLanguage?.[key] || fallback || key
  }

  const setLanguage = (lang: string) => {
    changeLanguage(lang)
  }
  
  return (
  <LanguageContext.Provider value={{ language, setLanguage, changeLanguage, currentLanguage, t }}>
  {children}
  </LanguageContext.Provider>
  )
  }

export const useLanguage = () => useContext(LanguageContext)
