"use client"

import { useState, useEffect, useRef } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import {
  Star,
  MessageCircle,
  AlertCircle,
  CheckCircle2,
  RefreshCw,
  Zap,
  Eye,
  EyeOff,
} from "lucide-react"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { db } from "@/lib/firebase"
import {
  collection,
  getDocs,
  doc,
  updateDoc,
  orderBy,
  query,
} from "firebase/firestore"

interface SyncedReview {
  id: string
  name: string
  location: string
  rating: number
  comment: string
  source: string
  date: string
  verified: boolean
  hidden: boolean
  smoobuId?: string
  autoGenerated?: boolean
  manualEntry?: boolean
  createdAt: number
}

export function SmoobuReviewsSync() {
  const [reviews, setReviews] = useState<SyncedReview[]>([])
  const [loading, setLoading] = useState(false)
  const [syncing, setSyncing] = useState(false)
  const [message, setMessage] = useState("")
  const [error, setError] = useState("")
  const [stats, setStats] = useState({ total: 0, visible: 0, hidden: 0, avgRating: 0 })
  const hasFetched = useRef(false)

  const fetchReviews = async () => {
    setLoading(true)
    try {
      const reviewsRef = collection(db, "reviews")
      const q = query(reviewsRef, orderBy("createdAt", "desc"))
      const snapshot = await getDocs(q)

      const allReviews: SyncedReview[] = snapshot.docs.map((docSnap) => ({
        id: docSnap.id,
        ...docSnap.data(),
      })) as SyncedReview[]

      setReviews(allReviews)

      const visible = allReviews.filter((r) => !r.hidden && r.rating > 0)
      const hidden = allReviews.filter((r) => r.hidden)
      const avgRating =
        visible.length > 0
          ? visible.reduce((sum, r) => sum + (r.rating || 0), 0) / visible.length
          : 0

      setStats({
        total: allReviews.length,
        visible: visible.length,
        hidden: hidden.length,
        avgRating: Math.round(avgRating * 10) / 10,
      })
    } catch (err) {
      console.error("[SmoobuReviewsSync] Error fetching reviews:", err)
      setError("Errore nel caricamento delle recensioni")
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    if (!hasFetched.current) {
      hasFetched.current = true
      fetchReviews()
    }
  }, [])

  const handleSync = async () => {
    setSyncing(true)
    setMessage("")
    setError("")
    try {
      const res = await fetch("/api/smoobu/sync-reviews", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({}),
      })
      const data = await res.json()
      if (data.success) {
        setMessage(data.message || `Sincronizzate ${data.created} nuove recensioni`)
        await fetchReviews()
      } else {
        setError(data.error || "Errore durante la sincronizzazione")
      }
    } catch (err) {
      setError("Errore di connessione durante la sincronizzazione")
    } finally {
      setSyncing(false)
    }
  }

  const toggleVisibility = async (reviewId: string, currentlyHidden: boolean) => {
    try {
      const reviewDoc = doc(db, "reviews", reviewId)
      await updateDoc(reviewDoc, { hidden: !currentlyHidden, updatedAt: Date.now() })
      setReviews((prev) =>
        prev.map((r) => (r.id === reviewId ? { ...r, hidden: !currentlyHidden } : r)),
      )
      const visible = reviews.filter((r) => (r.id === reviewId ? currentlyHidden : !r.hidden) && r.rating > 0)
      const hidden = reviews.filter((r) => (r.id === reviewId ? !currentlyHidden : r.hidden))
      const avgRating =
        visible.length > 0
          ? visible.reduce((sum, r) => sum + (r.rating || 0), 0) / visible.length
          : 0
      setStats({
        total: reviews.length,
        visible: visible.length,
        hidden: hidden.length,
        avgRating: Math.round(avgRating * 10) / 10,
      })
    } catch (err) {
      console.error("[SmoobuReviewsSync] Error toggling visibility:", err)
    }
  }

  const renderStars = (rating: number) => {
    return Array.from({ length: 5 }, (_, i) => (
      <Star
        key={i}
        className={`h-3.5 w-3.5 ${i < rating ? "fill-yellow-400 text-yellow-400" : "text-muted-foreground/30"}`}
      />
    ))
  }

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="text-lg flex items-center gap-2">
              <MessageCircle className="h-5 w-5" />
              Recensioni
            </CardTitle>
            <CardDescription>
              {stats.total} totali | {stats.visible} visibili | Media: {stats.avgRating}/5
            </CardDescription>
          </div>
          <div className="flex gap-2">
            <Button
              size="sm"
              variant="outline"
              onClick={fetchReviews}
              disabled={loading}
            >
              <RefreshCw className={`h-4 w-4 mr-1 ${loading ? "animate-spin" : ""}`} />
              Aggiorna
            </Button>
            <Button
              size="sm"
              onClick={handleSync}
              disabled={syncing}
            >
              <Zap className={`h-4 w-4 mr-1 ${syncing ? "animate-pulse" : ""}`} />
              {syncing ? "Sincronizzazione..." : "Sincronizza da Smoobu"}
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-3">
        {message && (
          <Alert>
            <CheckCircle2 className="h-4 w-4" />
            <AlertDescription>{message}</AlertDescription>
          </Alert>
        )}
        {error && (
          <Alert variant="destructive">
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}

        {loading ? (
          <div className="text-center text-muted-foreground py-8">Caricamento...</div>
        ) : reviews.length === 0 ? (
          <div className="text-center text-muted-foreground py-8">
            Nessuna recensione. Clicca "Sincronizza da Smoobu" per importare.
          </div>
        ) : (
          <div className="space-y-2 max-h-[400px] overflow-y-auto">
            {reviews.map((review) => (
              <div
                key={review.id}
                className={`flex items-start gap-3 p-3 rounded-lg border ${
                  review.hidden ? "opacity-50 bg-muted/30" : ""
                }`}
              >
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="font-medium text-sm truncate">{review.name}</span>
                    <div className="flex">{renderStars(review.rating)}</div>
                    <Badge variant="outline" className="text-[10px]">
                      {review.source}
                    </Badge>
                    {review.hidden && (
                      <Badge variant="secondary" className="text-[10px]">
                        Nascosta
                      </Badge>
                    )}
                  </div>
                  <p className="text-xs text-muted-foreground line-clamp-2">{review.comment}</p>
                  <span className="text-[10px] text-muted-foreground">{review.date}</span>
                </div>
                <Button
                  size="sm"
                  variant="ghost"
                  onClick={() => toggleVisibility(review.id, review.hidden)}
                  title={review.hidden ? "Mostra recensione" : "Nascondi recensione"}
                >
                  {review.hidden ? <Eye className="h-4 w-4" /> : <EyeOff className="h-4 w-4" />}
                </Button>
              </div>
            ))}
          </div>
        )}
      </CardContent>
    </Card>
  )
}
