"use client"

import { useState, useEffect, useRef } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import {
  Star,
  MessageCircle,
  AlertCircle,
  CheckCircle2,
  RefreshCw,
  Zap,
  Eye,
  EyeOff,
} from "lucide-react"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { Switch } from "@/components/ui/switch"

interface SyncedReview {
  id: string
  name: string
  rating: number
  comment: string
  source: string
  date: string
  location?: string
  hidden?: boolean
  autoGenerated?: boolean
  smoobuId?: string
  arrival?: string
  departure?: string
  channelName?: string
  nights?: number
}

interface ReviewStats {
  total: number
  visible: number
  hidden: number
  averageRating: number
  bySource: Record<string, number>
}

export function SmoobuReviewsSync() {
  const [syncing, setSyncing] = useState(false)
  const [loading, setLoading] = useState(true)
  const [result, setResult] = useState<{ success: boolean; message: string } | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [reviews, setReviews] = useState<SyncedReview[]>([])
  const [stats, setStats] = useState<ReviewStats | null>(null)
  const [togglingId, setTogglingId] = useState<string | null>(null)
  const hasLoadedRef = useRef(false)

  // Auto-load on mount
  useEffect(() => {
    if (!hasLoadedRef.current) {
      hasLoadedRef.current = true
      fetchReviews()
    }
  }, [])

  const fetchReviews = async () => {
    setLoading(true)
    try {
      const response = await fetch("/api/smoobu/sync-reviews?includeHidden=true&limit=200")
      const data = await response.json()
      if (response.ok && data.reviews) {
        setReviews(data.reviews)
      }
      if (data.stats) {
        setStats(data.stats)
      }
    } catch (err) {
      console.error("[Reviews] Error fetching reviews:", err)
    } finally {
      setLoading(false)
    }
  }

  // Sync reviews from Smoobu completed bookings
  const syncFromSmoobu = async () => {
    setSyncing(true)
    setError(null)
    setResult(null)

    try {
      const response = await fetch("/api/smoobu/sync-reviews", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({}), // default action = auto-sync
      })

      const data = await response.json()

      if (!response.ok) {
        throw new Error(data.error || "Errore nella sincronizzazione")
      }

      setResult({ success: true, message: data.message })
      // Refresh list
      fetchReviews()
    } catch (err) {
      setError(err instanceof Error ? err.message : "Errore sconosciuto")
    } finally {
      setSyncing(false)
    }
  }

  // Toggle visibility of a review
  const toggleVisibility = async (reviewId: string, currentlyHidden: boolean) => {
    setTogglingId(reviewId)
    try {
      const response = await fetch("/api/smoobu/sync-reviews", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          action: "toggle-visibility",
          reviewId,
          hidden: !currentlyHidden,
        }),
      })

      if (response.ok) {
        // Update locally
        setReviews((prev) =>
          prev.map((r) => (r.id === reviewId ? { ...r, hidden: !currentlyHidden } : r)),
        )
        // Update stats
        if (stats) {
          setStats({
            ...stats,
            visible: currentlyHidden ? stats.visible + 1 : stats.visible - 1,
            hidden: currentlyHidden ? stats.hidden - 1 : stats.hidden + 1,
          })
        }
      }
    } catch (err) {
      console.error("[Reviews] Error toggling visibility:", err)
    } finally {
      setTogglingId(null)
    }
  }

  const getSourceColor = (source: string) => {
    switch (source) {
      case "booking": return "bg-blue-600 text-white"
      case "airbnb": return "bg-pink-600 text-white"
      case "expedia": return "bg-yellow-600 text-white"
      case "direct": return "bg-emerald-600 text-white"
      default: return "bg-muted text-foreground"
    }
  }

  const getSourceLabel = (source: string) => {
    switch (source) {
      case "booking": return "Booking.com"
      case "airbnb": return "Airbnb"
      case "expedia": return "Expedia"
      case "direct": return "Diretta"
      case "manual": return "Manuale"
      default: return source
    }
  }

  const visibleReviews = reviews.filter((r) => !r.hidden)
  const hiddenReviews = reviews.filter((r) => r.hidden)

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <MessageCircle className="w-5 h-5" />
          Recensioni da Smoobu
        </CardTitle>
        <CardDescription>
          Le recensioni vengono create automaticamente dai soggiorni completati su Smoobu e mostrate
          nella pagina Recensioni e nella Home. Puoi nascondere quelle che non vuoi visualizzare.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        {/* Sync bar */}
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 rounded-lg border p-4 bg-muted/20">
          <div>
            <p className="text-sm font-medium">Sincronizzazione automatica</p>
            <p className="text-xs text-muted-foreground">
              Recupera i soggiorni completati da Smoobu e li aggiunge come recensioni verificate.
            </p>
          </div>
          <div className="flex gap-2">
            <Button
              onClick={fetchReviews}
              disabled={loading}
              variant="outline"
              size="sm"
            >
              {loading ? <RefreshCw className="w-4 h-4 animate-spin" /> : <RefreshCw className="w-4 h-4" />}
              <span className="ml-1.5">Aggiorna</span>
            </Button>
            <Button
              onClick={syncFromSmoobu}
              disabled={syncing}
              size="sm"
              className="bg-emerald-600 hover:bg-emerald-700 text-white"
            >
              {syncing ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Zap className="w-4 h-4" />}
              <span className="ml-1.5">Sincronizza da Smoobu</span>
            </Button>
          </div>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          <div className="rounded-lg border p-3 text-center">
            <p className="text-2xl font-bold">{stats?.visible ?? visibleReviews.length}</p>
            <p className="text-xs text-muted-foreground">Visibili</p>
          </div>
          <div className="rounded-lg border p-3 text-center">
            <p className="text-2xl font-bold text-muted-foreground">{stats?.hidden ?? hiddenReviews.length}</p>
            <p className="text-xs text-muted-foreground">Nascoste</p>
          </div>
          <div className="rounded-lg border p-3 text-center">
            <p className="text-2xl font-bold">{stats?.total ?? reviews.length}</p>
            <p className="text-xs text-muted-foreground">Totale</p>
          </div>
          <div className="rounded-lg border p-3 text-center">
            <div className="flex items-center justify-center gap-1">
              <p className="text-2xl font-bold">{stats?.averageRating?.toFixed(1) ?? "0"}</p>
              <Star className="w-4 h-4 fill-yellow-400 text-yellow-400" />
            </div>
            <p className="text-xs text-muted-foreground">Media voto</p>
          </div>
        </div>

        {/* Result messages */}
        {result && (
          <Alert className="bg-green-50 border-green-200">
            <CheckCircle2 className="h-4 w-4 text-green-600" />
            <AlertDescription>
              <p className="font-medium text-green-900">{result.message}</p>
            </AlertDescription>
          </Alert>
        )}

        {error && (
          <Alert variant="destructive">
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}

        {/* Reviews list with toggle */}
        {loading ? (
          <div className="space-y-2">
            {Array.from({ length: 4 }).map((_, i) => (
              <div key={i} className="h-16 rounded-md border animate-pulse bg-muted/30" />
            ))}
          </div>
        ) : reviews.length === 0 ? (
          <div className="text-center py-8 text-muted-foreground">
            <MessageCircle className="w-8 h-8 mx-auto mb-2 opacity-50" />
            <p className="text-sm">Nessuna recensione trovata.</p>
            <p className="text-xs">Clicca "Sincronizza da Smoobu" per importare i soggiorni completati.</p>
          </div>
        ) : (
          <div className="space-y-4">
            <h4 className="text-sm font-semibold flex items-center gap-2">
              Tutte le recensioni ({reviews.length})
            </h4>
            <div className="space-y-2 max-h-[400px] overflow-y-auto">
              {reviews.map((r) => (
                <div
                  key={r.id}
                  className={`flex items-start gap-3 rounded-md border p-3 text-sm transition-colors ${
                    r.hidden ? "opacity-50 bg-muted/20" : ""
                  }`}
                >
                  {/* Toggle */}
                  <div className="flex items-center pt-0.5">
                    <Switch
                      checked={!r.hidden}
                      disabled={togglingId === r.id}
                      onCheckedChange={() => toggleVisibility(r.id, !!r.hidden)}
                      aria-label={r.hidden ? "Mostra recensione" : "Nascondi recensione"}
                    />
                  </div>

                  {/* Stars */}
                  <div className="flex items-center gap-0.5 pt-0.5 flex-shrink-0">
                    {[...Array(5)].map((_, s) => (
                      <Star
                        key={s}
                        className={`w-3 h-3 ${
                          s < r.rating ? "fill-yellow-400 text-yellow-400" : "text-muted-foreground/30"
                        }`}
                      />
                    ))}
                  </div>

                  {/* Content */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className="font-medium">{r.name}</span>
                      <Badge className={`text-[10px] px-1.5 py-0 ${getSourceColor(r.source)}`}>
                        {getSourceLabel(r.source)}
                      </Badge>
                      {r.hidden && (
                        <Badge variant="outline" className="text-[10px] px-1.5 py-0">
                          <EyeOff className="w-2.5 h-2.5 mr-0.5" />
                          Nascosta
                        </Badge>
                      )}
                      {!r.hidden && (
                        <Badge variant="outline" className="text-[10px] px-1.5 py-0 border-green-300 text-green-700">
                          <Eye className="w-2.5 h-2.5 mr-0.5" />
                          Visibile
                        </Badge>
                      )}
                    </div>
                    <p className="text-muted-foreground line-clamp-2 mt-0.5">{r.comment}</p>
                    {r.date && <p className="text-xs text-muted-foreground mt-1">{r.date}</p>}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Source breakdown */}
        {stats?.bySource && Object.keys(stats.bySource).length > 0 && (
          <div className="pt-4 border-t">
            <h4 className="text-sm font-medium mb-2">Recensioni per fonte</h4>
            <div className="flex flex-wrap gap-2">
              {Object.entries(stats.bySource).map(([src, count]) => (
                <Badge key={src} className={`${getSourceColor(src)}`}>
                  <Star className="w-3 h-3 mr-1" />
                  {getSourceLabel(src)}: {count}
                </Badge>
              ))}
            </div>
          </div>
        )}

        {/* Info footer */}
        <div className="pt-4 border-t space-y-2">
          <h4 className="text-sm font-medium">Come funziona</h4>
          <div className="space-y-1.5 text-xs text-muted-foreground">
            <div className="flex items-start gap-2">
              <Zap className="w-3.5 h-3.5 mt-0.5 flex-shrink-0 text-emerald-600" />
              <p>Le recensioni vengono create automaticamente dai soggiorni completati su Smoobu</p>
            </div>
            <div className="flex items-start gap-2">
              <Eye className="w-3.5 h-3.5 mt-0.5 flex-shrink-0 text-blue-600" />
              <p>Usa il toggle per nascondere/mostrare le recensioni nella pagina pubblica e nella Home</p>
            </div>
            <div className="flex items-start gap-2">
              <CheckCircle2 className="w-3.5 h-3.5 mt-0.5 flex-shrink-0 text-green-600" />
              <p>Le recensioni visibili appaiono automaticamente senza bisogno di intervento manuale</p>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}
