export const ROOMS = [
  {
    id: "1",
    name: "Camera Familiare con Balcone",
    description: "Camera matrimoniale e balcone privato",
    images: ["/images/room-2.jpg", "/images/room-1.jpg"],
    price: 180,
    originalPrice: 220,
    guests: 4,
    beds: 2,
    bathrooms: 2,
    size: 35,
    amenities: [
      "Vista luogo di interesse",
      "vista mare",
      "Balcone privato",
      "WiFi gratuito",
      "Minibar",
      "Aria condizionata",
      "TV satellitare",
    ],
    rating: 4.9,
    reviews: 56,
    featured: true,
  },
  {
    id: "2",
    name: "Camera Matrimoniale con Vasca Idromassaggio",
    description: "Elegante camera con vasca idromassaggio e arredi di lusso",
    images: ["/images/room-1.jpg", "/images/room-2.jpg"],
    price: 150,
    originalPrice: 180,
    guests: 4,
    beds: 2,
    bathrooms: 1,
    size: 33,
    amenities: [
      "Aria condizionata",
      "TV satellitare",
      "Vasca idromassaggio",
      "Asciugacapelli",
      "WiFi gratuito",
      "Minibar",
    ],
    rating: 4.9,
    reviews: 56,
    featured: false,
  },
] as const

export type Room = (typeof ROOMS)[number]
